#go build
#docker build -t ctc_api .
#docker tag ctc_api:latest rehfran/ctc_api:latest
#docker login
#docker push rehfran/ctc_api:latest
#docker compose up

version: "3.9"
services:
  ctc_api:
    container_name: ctc_api
    networks:
      - ctc_network
    image: "rehfran/ctc_api:latest"
    depends_on:
      - mongo_db
    ports:
      - "8080:8080"
    environment:
      - "mongo_var=mongodb://mongo_db:27017"
  mongo_db:
    container_name: mongodb
    ports:
      - "27017:27017"
    image: "mongo:5"
    networks:
      - ctc_network
    volumes:
      - ./mongo-volume:/data/db

networks:
  ctc_network:
    driver: bridge